### ISSUE TITLE
Missing information on pyquaternion dependency

### ISSUE THREAD

**Issue by xEnVrE** [hsp-panda/panda_grasp_server#3]
It seems that `save_grasp`, that is in turn required by the grasp sever, depends on `pyquaternion`

https://github.com/hsp-panda/panda_grasp_server/blob/0b0d18445d1acfb98e7daef305306a1122799d42/src/panda_grasp_server/save_grasp.py#L3

however, the repository is not providing this information.

Is there a way to use the `package.xml` and `rosdep` to warn the user about that? (Or can we just add this information in the README?)

**Comment by fbottarel** [comment]
I found some [official ros docs](https://docs.ros.org/en/melodic/api/catkin/html/user_guide/setup_dot_py.html) addressing this: 

> If you have written non-ROS Python packages before, you have probably used the requires field in the distuils setup function. This field, however, has no meaning in ROS. All your Python dependencies should be specified in package.xml as e.g. <run_depend>python-numpy</run_depend> (for older version 1 of package.xml) or <exec_depend>python-numpy</exec_depend> (if you use format 2 of package.xml). Not all Python or pip packages are mapped to ROS dependencies. For a quick check, try running rosdep resolve python-mypackage or rosdep resolve python-mypackage-pip if you want to add a dependency on mypackage Python package. If these calls return error, you may want to search through the python.yaml file in rosdep for similar names.

I would try to do as the docs suggest, and if it doesn't work (e.g. pyquaternion is not mapped in rosdep) just make a `requirements.txt`. 

Update: I have tried, there is no rosdep mapping for pyquaternion yet. I opened [a pull request](https://github.com/ros/rosdistro/pull/27595) for it, if it gets accepted I will update `package.xml` with something like 

```
<run_depend>pyquaternion-pip</run_depend>
```

or 
```
<exec_depend>pyquaternion-pip</exec_depend>
```

**Comment by xEnVrE** [comment]
Thank you @fbottarel, let's see then if the PR gets accepted.

**Comment by fbottarel** [comment]
Apparently the PR didn't need to get accepted since `pyquaternion` is already present as a rosdep. 

By adding `pyquaternion` as a dependency in the `package.xml` file we obtain

```
$ rosdep check --ignore-src panda_grasp_server
System dependencies have not been satisfied:
apt	ros-melodic-pyquaternion
```

In fact, `rosdep` resolves pyquaternion to a system dependency that is installable via `apt`
```
$ rosdep resolve pyquaternion
#apt
ros-melodic-pyquaternion
$ sudo apt install ros-melodic-pyquaternion
```

and this fixes the problem. I will simply add `pyquaternion` in the manifest.
