### ISSUE TITLE
Regarding branches...

### ISSUE THREAD

**Issue by fbottarel** [hsp-panda/panda_grasp_server#8]
@safoex I see you have created a couple of branches (pushed with my username, whoopsy daisy) in this repo for what I assume are experimental tests. While it might be fine for now, on the long run these repos are going to become a hot mess. I encourage you to make either a fork of this repo and push there, or just make a standalone script somewhere else (after all, this ROS node is supposed to expose a service-based interface).

Seems like I need to un-hook my account from the workstation as well. 🧱

**Comment by fbottarel** [comment]
On the same topic, I realize the `calib.py` script does not really belong there, since it's not even a complete working pipeline. I guess I will need to organize my own stuff better.

**Comment by safoex** [comment]
Sorry for messing up the stuff, I will move this code soon to playground. 
By the way, what do you think about adding a .gitignore file (e.g. with *.pyc) ?

**Comment by fbottarel** [comment]
@safoex done!
